"""
test_level4_physical_oracle_d3.py

Level 4A/B/C validation for the CURRENT v2 architecture.

This test intentionally does NOT use defect_graph or decoder logic as an
oracle. Ground truth is obtained directly from the S0 stabilizer incidence
matrices by exhaustive enumeration of all 2^13 physical data-qubit errors.

Scope:
  A. Boundary singleton oracle: minimum physical weight for each realizable
     singleton syndrome, reported by physical boundary side membership.
  B. Check-to-check oracle: minimum physical weight for every realizable
     two-check syndrome.
  C. Recovery-ready data: the exact physical representative masks are kept
     so graph witnesses can later be checked against the oracle.

Important methodological limitation:
  A singleton syndrome can be generated by a physical boundary qubit, but
  "which boundary it terminates at" is not determined by syndrome alone when
  a representative lies on a corner or can be represented by multiple
  equivalent errors. Therefore this first oracle records boundary incidence
  candidates for the minimum representatives and does not silently invent a
  unique termination semantics. Exact graph-boundary semantics must be
  compared against these physical representatives explicitly.
"""

from collections import defaultdict
import sys

sys.path.insert(0, "src")

from decoder_lib_v2 import build_decoding_graph, CheckType, popcount


def sector_data(graph, sector):
    """Return (check_ids, check_masks) for one CSS sector."""
    rows = [
        (stab.check_id, graph.check_masks[idx])
        for idx, stab in enumerate(graph.stabilizers)
        if stab.check_type == sector
    ]
    rows.sort()
    return [x[0] for x in rows], [x[1] for x in rows]


def sector_syndrome(error_mask, check_masks):
    """Return a local-sector syndrome bit mask."""
    synd = 0
    for k, check_mask in enumerate(check_masks):
        if popcount(error_mask & check_mask) & 1:
            synd |= 1 << k
    return synd


def singleton_check_id(synd, check_ids):
    """Return the check id if synd is exactly one local defect, else None."""
    if synd == 0 or synd & (synd - 1):
        return None
    local_idx = synd.bit_length() - 1
    return check_ids[local_idx]


def pair_check_ids(synd, check_ids):
    """Return sorted check ids if synd has exactly two defects, else None."""
    if synd.bit_count() != 2:
        return None
    indices = [i for i in range(len(check_ids)) if (synd >> i) & 1]
    return tuple(sorted((check_ids[indices[0]], check_ids[indices[1]])))


def boundary_sides(graph, error_mask):
    """Return physical boundary sides touched by data qubits in error_mask."""
    sides = set()
    max_coord = 2 * graph.d - 2
    for q, pos in graph.data_positions.items():
        if not ((error_mask >> q) & 1):
            continue
        i, j = pos
        if i == 0:
            sides.add("top")
        if i == max_coord:
            sides.add("bottom")
        if j == 0:
            sides.add("left")
        if j == max_coord:
            sides.add("right")
    return tuple(sorted(sides))


def build_physical_oracle(graph):
    """Exhaustively compute minimum physical representatives by sector."""
    total = 1 << graph.n_data
    result = {}

    for sector in (CheckType.Z, CheckType.X):
        check_ids, check_masks = sector_data(graph, sector)
        by_syndrome = {}

        for error in range(total):
            synd = sector_syndrome(error, check_masks)
            weight = popcount(error)
            entry = by_syndrome.get(synd)
            if entry is None or weight < entry["weight"]:
                by_syndrome[synd] = {
                    "weight": weight,
                    "masks": [error],
                }
            elif weight == entry["weight"]:
                entry["masks"].append(error)

        result[sector] = {
            "check_ids": check_ids,
            "check_masks": check_masks,
            "by_syndrome": by_syndrome,
        }

    return result


def build_boundary_oracle(graph, physical_oracle):
    """
    Extract minimum physical representatives for singleton syndromes.

    Key: (sector, check_id)
    Value: {
        weight: minimum physical weight,
        masks: all minimum-weight representatives,
        boundary_sides: union of physical sides touched by those masks,
    }

    This deliberately avoids claiming that every touched side is a valid
    graph termination. That semantic question is exactly what Level 4A is
    intended to validate.
    """
    result = {}
    for sector, data in physical_oracle.items():
        check_ids = data["check_ids"]
        for synd, entry in data["by_syndrome"].items():
            cid = singleton_check_id(synd, check_ids)
            if cid is None:
                continue
            sides = set()
            for mask in entry["masks"]:
                sides.update(boundary_sides(graph, mask))
            result[(sector, cid)] = {
                "weight": entry["weight"],
                "masks": entry["masks"],
                "boundary_sides": tuple(sorted(sides)),
            }
    return result


def build_pair_oracle(graph, physical_oracle):
    """Extract minimum physical representatives for all two-check syndromes."""
    result = {}
    for sector, data in physical_oracle.items():
        check_ids = data["check_ids"]
        for synd, entry in data["by_syndrome"].items():
            pair = pair_check_ids(synd, check_ids)
            if pair is None:
                continue
            result[(sector, pair[0], pair[1])] = {
                "weight": entry["weight"],
                "masks": entry["masks"],
            }
    return result


def graph_boundary_formula(graph, sector, check_id, side):
    """Read the current v2 boundary cost formula without using defect_graph."""
    for stab in graph.stabilizers:
        if stab.check_id != check_id or stab.check_type != sector:
            continue
        i, j = stab.position
        max_coord = 2 * graph.d - 2
        if sector == CheckType.Z:
            if side == "top":
                return i / 2 + 1
            if side == "bottom":
                return (max_coord - i) / 2 + 1
        else:
            if side == "left":
                return j / 2 + 1
            if side == "right":
                return (max_coord - j) / 2 + 1
    return None


def graph_pair_distance(graph, sector, c1, c2):
    """
    Return current graph pair distance if the v2 graph exposes one.

    The present v2 baseline has defect_graph={} and therefore returns None.
    This makes the test an explicit precondition check rather than silently
    substituting a different graph implementation.
    """
    defect_graph = getattr(graph, "defect_graph", {})
    if not defect_graph:
        return None
    # No pair-distance contract exists yet in current v2.
    return None


def test_level4a_boundary_oracle_d3():
    graph = build_decoding_graph(3)
    oracle = build_physical_oracle(graph)
    boundary = build_boundary_oracle(graph, oracle)

    print("=" * 70)
    print("LEVEL 4A: Physical Boundary Oracle (d=3)")
    print("=" * 70)

    failures = []
    for (sector, cid), entry in sorted(boundary.items(), key=lambda x: (x[0][0].value, x[0][1])):
        sides = entry["boundary_sides"]
        print(
            f"  {sector.value}-check {cid}: min_weight={entry['weight']}, "
            f"minimum representatives={len(entry['masks'])}, physical_sides={sides}"
        )

        expected_sides = ("top", "bottom") if sector == CheckType.Z else ("left", "right")
        for side in expected_sides:
            formula = graph_boundary_formula(graph, sector, cid, side)
            if formula is None:
                failures.append((sector.value, cid, side, "missing formula"))

    assert not failures, f"Boundary formula lookup failures: {failures}"
    print("\nBoundary physical representatives computed independently.")
    print("Current v2 formula is reported for comparison; no claim of exactness is made here.")


def test_level4b_pair_oracle_d3():
    graph = build_decoding_graph(3)
    oracle = build_physical_oracle(graph)
    pairs = build_pair_oracle(graph, oracle)

    print("=" * 70)
    print("LEVEL 4B: Physical Check-to-Check Oracle (d=3)")
    print("=" * 70)

    for (sector, c1, c2), entry in sorted(pairs.items(), key=lambda x: (x[0][0].value, x[0][1], x[0][2])):
        graph_distance = graph_pair_distance(graph, sector, c1, c2)
        print(
            f"  {sector.value}-pair ({c1},{c2}): "
            f"phys_min={entry['weight']}, representatives={len(entry['masks'])}, "
            f"graph_distance={graph_distance}"
        )

    print("\nPair oracle computed independently from S0 incidence.")
    print("Current v2 has no defect graph yet, so pair-distance comparison is intentionally pending.")


def test_level4c_oracle_syndrome_reproduction_d3():
    """Verify every stored oracle representative reproduces its syndrome."""
    graph = build_decoding_graph(3)
    oracle = build_physical_oracle(graph)

    print("=" * 70)
    print("LEVEL 4C: Oracle Syndrome Reproduction (d=3)")
    print("=" * 70)

    checked = 0
    for sector, data in oracle.items():
        check_ids = data["check_ids"]
        check_masks = data["check_masks"]
        for synd, entry in data["by_syndrome"].items():
            for mask in entry["masks"]:
                recovered = sector_syndrome(mask, check_masks)
                assert recovered == synd, (
                    f"{sector.value}: mask {mask} reproduces {recovered}, expected {synd}"
                )
                checked += 1

    print(f"  Verified minimum representatives: {checked}")
    print("  ALL ORACLE REPRESENTATIVES REPRODUCE THEIR SYNDROMES")


if __name__ == "__main__":
    test_level4a_boundary_oracle_d3()
    test_level4b_pair_oracle_d3()
    test_level4c_oracle_syndrome_reproduction_d3()
